/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.easywall.EasyWallRuntimeModule;
import org.xtext.example.easywall.EasyWallStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class EasyWallIdeSetup extends EasyWallStandaloneSetup {
  @Override
  public Injector createInjector() {
    EasyWallRuntimeModule _easyWallRuntimeModule = new EasyWallRuntimeModule();
    EasyWallIdeModule _easyWallIdeModule = new EasyWallIdeModule();
    return Guice.createInjector(Modules2.mixin(_easyWallRuntimeModule, _easyWallIdeModule));
  }
}
