/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.easywall.ide.contentassist.antlr.internal.InternalEasyWallParser;
import org.xtext.example.easywall.services.EasyWallGrammarAccess;

public class EasyWallParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(EasyWallGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, EasyWallGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEFProgramAccess().getAlternatives_1(), "rule__EFProgram__Alternatives_1");
			builder.put(grammarAccess.getEFMemberAccess().getAlternatives(), "rule__EFMember__Alternatives");
			builder.put(grammarAccess.getEFFieldAccess().getAlternatives_0(), "rule__EFField__Alternatives_0");
			builder.put(grammarAccess.getEFTypedDeclarationAccess().getAlternatives_2(), "rule__EFTypedDeclaration__Alternatives_2");
			builder.put(grammarAccess.getEFVariableDeclarationAccess().getAlternatives_0(), "rule__EFVariableDeclaration__Alternatives_0");
			builder.put(grammarAccess.getEFStatementAccess().getAlternatives(), "rule__EFStatement__Alternatives");
			builder.put(grammarAccess.getEFIfBlockAccess().getAlternatives(), "rule__EFIfBlock__Alternatives");
			builder.put(grammarAccess.getEFUnaryExpressionAccess().getAlternatives(), "rule__EFUnaryExpression__Alternatives");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getAlternatives(), "rule__EFPrimaryExpression__Alternatives");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getValueAlternatives_2_1_0(), "rule__EFPrimaryExpression__ValueAlternatives_2_1_0");
			builder.put(grammarAccess.getEFOrAccess().getAlternatives(), "rule__EFOr__Alternatives");
			builder.put(grammarAccess.getEFAndAccess().getAlternatives(), "rule__EFAnd__Alternatives");
			builder.put(grammarAccess.getEFNotAccess().getAlternatives(), "rule__EFNot__Alternatives");
			builder.put(grammarAccess.getEFEqualOperatorsAccess().getAlternatives(), "rule__EFEqualOperators__Alternatives");
			builder.put(grammarAccess.getEFRelOperatorsAccess().getAlternatives(), "rule__EFRelOperators__Alternatives");
			builder.put(grammarAccess.getEFNetworkNativeTypeAccess().getAlternatives(), "rule__EFNetworkNativeType__Alternatives");
			builder.put(grammarAccess.getEFRulesTypesAccess().getAlternatives(), "rule__EFRulesTypes__Alternatives");
			builder.put(grammarAccess.getEFProgramAccess().getGroup(), "rule__EFProgram__Group__0");
			builder.put(grammarAccess.getEFHeaderAccess().getGroup(), "rule__EFHeader__Group__0");
			builder.put(grammarAccess.getEFHeaderAccess().getGroup_1(), "rule__EFHeader__Group_1__0");
			builder.put(grammarAccess.getEFImportsAccess().getGroup(), "rule__EFImports__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
			builder.put(grammarAccess.getEFFireClassAccess().getGroup(), "rule__EFFireClass__Group__0");
			builder.put(grammarAccess.getEFFieldAccess().getGroup(), "rule__EFField__Group__0");
			builder.put(grammarAccess.getEFTypedDeclarationAccess().getGroup(), "rule__EFTypedDeclaration__Group__0");
			builder.put(grammarAccess.getEFVariableDeclarationAccess().getGroup(), "rule__EFVariableDeclaration__Group__0");
			builder.put(grammarAccess.getEFMethodAccess().getGroup(), "rule__EFMethod__Group__0");
			builder.put(grammarAccess.getEFMethodAccess().getGroup_3(), "rule__EFMethod__Group_3__0");
			builder.put(grammarAccess.getEFMethodAccess().getGroup_3_1(), "rule__EFMethod__Group_3_1__0");
			builder.put(grammarAccess.getEFBlockAccess().getGroup(), "rule__EFBlock__Group__0");
			builder.put(grammarAccess.getEFStatementAccess().getGroup_2(), "rule__EFStatement__Group_2__0");
			builder.put(grammarAccess.getEFReturnAccess().getGroup(), "rule__EFReturn__Group__0");
			builder.put(grammarAccess.getEFIfStatementAccess().getGroup(), "rule__EFIfStatement__Group__0");
			builder.put(grammarAccess.getEFIfStatementAccess().getGroup_5(), "rule__EFIfStatement__Group_5__0");
			builder.put(grammarAccess.getEFAssignmentAccess().getGroup(), "rule__EFAssignment__Group__0");
			builder.put(grammarAccess.getEFAssignmentAccess().getGroup_1(), "rule__EFAssignment__Group_1__0");
			builder.put(grammarAccess.getEFOrExpressionAccess().getGroup(), "rule__EFOrExpression__Group__0");
			builder.put(grammarAccess.getEFOrExpressionAccess().getGroup_1(), "rule__EFOrExpression__Group_1__0");
			builder.put(grammarAccess.getEFAndExpressionAccess().getGroup(), "rule__EFAndExpression__Group__0");
			builder.put(grammarAccess.getEFAndExpressionAccess().getGroup_1(), "rule__EFAndExpression__Group_1__0");
			builder.put(grammarAccess.getEFEqualExpressionAccess().getGroup(), "rule__EFEqualExpression__Group__0");
			builder.put(grammarAccess.getEFEqualExpressionAccess().getGroup_1(), "rule__EFEqualExpression__Group_1__0");
			builder.put(grammarAccess.getEFRelExpressionAccess().getGroup(), "rule__EFRelExpression__Group__0");
			builder.put(grammarAccess.getEFRelExpressionAccess().getGroup_1(), "rule__EFRelExpression__Group_1__0");
			builder.put(grammarAccess.getEFUnaryExpressionAccess().getGroup_0(), "rule__EFUnaryExpression__Group_0__0");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getGroup_0(), "rule__EFPrimaryExpression__Group_0__0");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getGroup_1(), "rule__EFPrimaryExpression__Group_1__0");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getGroup_2(), "rule__EFPrimaryExpression__Group_2__0");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getGroup_3(), "rule__EFPrimaryExpression__Group_3__0");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getGroup_4(), "rule__EFPrimaryExpression__Group_4__0");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getGroup_5(), "rule__EFPrimaryExpression__Group_5__0");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getGroup_6(), "rule__EFPrimaryExpression__Group_6__0");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getGroup_7(), "rule__EFPrimaryExpression__Group_7__0");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getGroup_8(), "rule__EFPrimaryExpression__Group_8__0");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getGroup_8_3(), "rule__EFPrimaryExpression__Group_8_3__0");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getGroup_8_3_1(), "rule__EFPrimaryExpression__Group_8_3_1__0");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getGroup_9(), "rule__EFPrimaryExpression__Group_9__0");
			builder.put(grammarAccess.getEFSelectionExpressionAccess().getGroup(), "rule__EFSelectionExpression__Group__0");
			builder.put(grammarAccess.getEFSelectionExpressionAccess().getGroup_1(), "rule__EFSelectionExpression__Group_1__0");
			builder.put(grammarAccess.getEFSelectionExpressionAccess().getGroup_1_3(), "rule__EFSelectionExpression__Group_1_3__0");
			builder.put(grammarAccess.getEFSelectionExpressionAccess().getGroup_1_3_1(), "rule__EFSelectionExpression__Group_1_3_1__0");
			builder.put(grammarAccess.getEFSelectionExpressionAccess().getGroup_1_3_1_1(), "rule__EFSelectionExpression__Group_1_3_1_1__0");
			builder.put(grammarAccess.getEFRuleClassAccess().getGroup(), "rule__EFRuleClass__Group__0");
			builder.put(grammarAccess.getEFProgramAccess().getRuleAssignment_1_0(), "rule__EFProgram__RuleAssignment_1_0");
			builder.put(grammarAccess.getEFProgramAccess().getFirewallAssignment_1_1(), "rule__EFProgram__FirewallAssignment_1_1");
			builder.put(grammarAccess.getEFHeaderAccess().getNameAssignment_1_1(), "rule__EFHeader__NameAssignment_1_1");
			builder.put(grammarAccess.getEFHeaderAccess().getImportsAssignment_2(), "rule__EFHeader__ImportsAssignment_2");
			builder.put(grammarAccess.getEFfirewallAccess().getFirewallAssignment(), "rule__EFfirewall__FirewallAssignment");
			builder.put(grammarAccess.getEFImportsAccess().getImportedNamespaceAssignment_1(), "rule__EFImports__ImportedNamespaceAssignment_1");
			builder.put(grammarAccess.getEFFireClassAccess().getNameAssignment_1(), "rule__EFFireClass__NameAssignment_1");
			builder.put(grammarAccess.getEFFireClassAccess().getMembersAssignment_3(), "rule__EFFireClass__MembersAssignment_3");
			builder.put(grammarAccess.getEFTypedDeclarationAccess().getNameAssignment_0(), "rule__EFTypedDeclaration__NameAssignment_0");
			builder.put(grammarAccess.getEFTypedDeclarationAccess().getRuletypeAssignment_2_0(), "rule__EFTypedDeclaration__RuletypeAssignment_2_0");
			builder.put(grammarAccess.getEFTypedDeclarationAccess().getNativetypeAssignment_2_1(), "rule__EFTypedDeclaration__NativetypeAssignment_2_1");
			builder.put(grammarAccess.getEFVariableDeclarationAccess().getExpressionAssignment_3(), "rule__EFVariableDeclaration__ExpressionAssignment_3");
			builder.put(grammarAccess.getEFMethodAccess().getParamsAssignment_3_0(), "rule__EFMethod__ParamsAssignment_3_0");
			builder.put(grammarAccess.getEFMethodAccess().getParamsAssignment_3_1_1(), "rule__EFMethod__ParamsAssignment_3_1_1");
			builder.put(grammarAccess.getEFMethodAccess().getBodyAssignment_5(), "rule__EFMethod__BodyAssignment_5");
			builder.put(grammarAccess.getEFBlockAccess().getStatementsAssignment_2(), "rule__EFBlock__StatementsAssignment_2");
			builder.put(grammarAccess.getEFReturnAccess().getExpressionAssignment_1(), "rule__EFReturn__ExpressionAssignment_1");
			builder.put(grammarAccess.getEFIfStatementAccess().getExpressionAssignment_2(), "rule__EFIfStatement__ExpressionAssignment_2");
			builder.put(grammarAccess.getEFIfStatementAccess().getThenBlockAssignment_4(), "rule__EFIfStatement__ThenBlockAssignment_4");
			builder.put(grammarAccess.getEFIfStatementAccess().getElseBlockAssignment_5_1(), "rule__EFIfStatement__ElseBlockAssignment_5_1");
			builder.put(grammarAccess.getEFIfBlockAccess().getStatementsAssignment_0(), "rule__EFIfBlock__StatementsAssignment_0");
			builder.put(grammarAccess.getEFAssignmentAccess().getRightAssignment_1_2(), "rule__EFAssignment__RightAssignment_1_2");
			builder.put(grammarAccess.getEFOrExpressionAccess().getRightAssignment_1_2(), "rule__EFOrExpression__RightAssignment_1_2");
			builder.put(grammarAccess.getEFAndExpressionAccess().getRightAssignment_1_2(), "rule__EFAndExpression__RightAssignment_1_2");
			builder.put(grammarAccess.getEFEqualExpressionAccess().getRightAssignment_1_2(), "rule__EFEqualExpression__RightAssignment_1_2");
			builder.put(grammarAccess.getEFRelExpressionAccess().getRightAssignment_1_2(), "rule__EFRelExpression__RightAssignment_1_2");
			builder.put(grammarAccess.getEFUnaryExpressionAccess().getExpressionAssignment_0_2(), "rule__EFUnaryExpression__ExpressionAssignment_0_2");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getValueAssignment_0_1(), "rule__EFPrimaryExpression__ValueAssignment_0_1");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getValueAssignment_1_1(), "rule__EFPrimaryExpression__ValueAssignment_1_1");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getValueAssignment_2_1(), "rule__EFPrimaryExpression__ValueAssignment_2_1");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getTypeAssignment_3_1(), "rule__EFPrimaryExpression__TypeAssignment_3_1");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getTypeAssignment_6_2(), "rule__EFPrimaryExpression__TypeAssignment_6_2");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getExpressionAssignment_7_2(), "rule__EFPrimaryExpression__ExpressionAssignment_7_2");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getFunctionNameAssignment_8_1(), "rule__EFPrimaryExpression__FunctionNameAssignment_8_1");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getArgsAssignment_8_3_0(), "rule__EFPrimaryExpression__ArgsAssignment_8_3_0");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getArgsAssignment_8_3_1_1(), "rule__EFPrimaryExpression__ArgsAssignment_8_3_1_1");
			builder.put(grammarAccess.getEFPrimaryExpressionAccess().getSymbolAssignment_9_1(), "rule__EFPrimaryExpression__SymbolAssignment_9_1");
			builder.put(grammarAccess.getEFSelectionExpressionAccess().getMemberAssignment_1_2(), "rule__EFSelectionExpression__MemberAssignment_1_2");
			builder.put(grammarAccess.getEFSelectionExpressionAccess().getArgsAssignment_1_3_1_0(), "rule__EFSelectionExpression__ArgsAssignment_1_3_1_0");
			builder.put(grammarAccess.getEFSelectionExpressionAccess().getArgsAssignment_1_3_1_1_1(), "rule__EFSelectionExpression__ArgsAssignment_1_3_1_1_1");
			builder.put(grammarAccess.getEFRuleAccess().getRulesAssignment(), "rule__EFRule__RulesAssignment");
			builder.put(grammarAccess.getEFRuleClassAccess().getNameAssignment_1(), "rule__EFRuleClass__NameAssignment_1");
			builder.put(grammarAccess.getEFRuleClassAccess().getTypeAssignment_3(), "rule__EFRuleClass__TypeAssignment_3");
			builder.put(grammarAccess.getEFRuleClassAccess().getMembersAssignment_5(), "rule__EFRuleClass__MembersAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private EasyWallGrammarAccess grammarAccess;

	@Override
	protected InternalEasyWallParser createParser() {
		InternalEasyWallParser result = new InternalEasyWallParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public EasyWallGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EasyWallGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
