/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EasyWallUiModule extends AbstractEasyWallUiModule {
  public EasyWallUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
