/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.tests;

import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.example.easywall.easyWall.EFProgram;

@ExtendWith(InjectionExtension.class)
@InjectWith(EasyWallInjectorProvider.class)
@SuppressWarnings("all")
public class EasyWallParsingTest {
  @Inject
  private ParseHelper<EFProgram> parseHelper;

  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("firewall fire {}");
      _builder.newLine();
      final EFProgram result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void firstProgram() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("pack my.fire;");
      _builder.newLine();
      _builder.append("import net.rules.*;");
      _builder.newLine();
      _builder.append("firewall MyFirewall {");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("set ipAddress : netip;");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("var portNumber : netport;");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("fun checkPort : netport (param : netport) {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("var result : netport = param;");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("if (result == portNumber) {");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("return result;");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("} else {");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("return portNumber;");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      EFProgram result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void ruleINDirection() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("pack my.fire;");
      _builder.newLine();
      _builder.append("import net.rules.*;");
      _builder.newLine();
      _builder.append("rule r at ApplicationLayer{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("var dir : direction = in;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      EFProgram result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void ruleOUTDirection() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("pack my.fire;");
      _builder.newLine();
      _builder.append("import net.rules.*;");
      _builder.newLine();
      _builder.append("rule r at ApplicationLayer{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("var dir : direction = out;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      EFProgram result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void IPv4SyntaxTest() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("pack my.fire;");
      _builder.newLine();
      _builder.append("import net.rules.*;");
      _builder.newLine();
      _builder.append("rule r at ApplicationLayer{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("var ip : netip = 192.168.0.1;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      EFProgram result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void IPv6SyntaxTest() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("pack my.fire;");
      _builder.newLine();
      _builder.append("import net.rules.*;");
      _builder.newLine();
      _builder.append("rule r at ApplicationLayer{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("var ip : netipv6 = 2001:0db8:0300:0000:0000:0000:0000:0001;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      EFProgram result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void NetPortSyntaxTest() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("pack my.fire;");
      _builder.newLine();
      _builder.append("import net.rules.*;");
      _builder.newLine();
      _builder.append("rule r at ApplicationLayer{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("var port : netport = :443;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      EFProgram result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void NetMaskSyntaxTest() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("pack my.fire;");
      _builder.newLine();
      _builder.append("import net.rules.*;");
      _builder.newLine();
      _builder.append("rule r at ApplicationLayer{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("var mask : netmask = /24;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      EFProgram result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void NetSyntaxTest1() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("pack my.fire;");
      _builder.newLine();
      _builder.append("import net.rules.*;");
      _builder.newLine();
      _builder.append("rule r at ApplicationLayer{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("var mynet : network = 192.168.1.0/24;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      EFProgram result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void NetSyntaxTest2() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("pack my.fire;");
      _builder.newLine();
      _builder.append("import net.rules.*;");
      _builder.newLine();
      _builder.append("rule r at ApplicationLayer{");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("var mask : netmask = /24;");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("var mynet : network = 192.168.1.0/mask;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      EFProgram result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void NetSyntaxTest3() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("pack my.fire;");
      _builder.newLine();
      _builder.append("import net.rules.*;");
      _builder.newLine();
      _builder.append("rule r at ApplicationLayer{");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("var mask : netmask = /24;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("var ip : netip = 192.168.0.1;");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("var mynet : network = ip/mask;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      EFProgram result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void NetSyntaxTest4() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("pack my.fire;");
      _builder.newLine();
      _builder.append("import net.rules.*;");
      _builder.newLine();
      _builder.append("rule r at ApplicationLayer{");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("var ip : netip = 192.168.0.1;");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("var mynet : network = ip/24;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      EFProgram result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
