/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage
 * @generated
 */
public interface EasyWallFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EasyWallFactory eINSTANCE = org.xtext.example.easywall.easyWall.impl.EasyWallFactoryImpl.init();

  /**
   * Returns a new object of class '<em>EF Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Program</em>'.
   * @generated
   */
  EFProgram createEFProgram();

  /**
   * Returns a new object of class '<em>EF Header</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Header</em>'.
   * @generated
   */
  EFHeader createEFHeader();

  /**
   * Returns a new object of class '<em>EFfirewall</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EFfirewall</em>'.
   * @generated
   */
  EFfirewall createEFfirewall();

  /**
   * Returns a new object of class '<em>EF Imports</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Imports</em>'.
   * @generated
   */
  EFImports createEFImports();

  /**
   * Returns a new object of class '<em>EF Fire Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Fire Class</em>'.
   * @generated
   */
  EFFireClass createEFFireClass();

  /**
   * Returns a new object of class '<em>EF Member</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Member</em>'.
   * @generated
   */
  EFMember createEFMember();

  /**
   * Returns a new object of class '<em>EF Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Field</em>'.
   * @generated
   */
  EFField createEFField();

  /**
   * Returns a new object of class '<em>EF Typed Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Typed Declaration</em>'.
   * @generated
   */
  EFTypedDeclaration createEFTypedDeclaration();

  /**
   * Returns a new object of class '<em>EF Variable Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Variable Declaration</em>'.
   * @generated
   */
  EFVariableDeclaration createEFVariableDeclaration();

  /**
   * Returns a new object of class '<em>EF Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Method</em>'.
   * @generated
   */
  EFMethod createEFMethod();

  /**
   * Returns a new object of class '<em>EF Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Parameter</em>'.
   * @generated
   */
  EFParameter createEFParameter();

  /**
   * Returns a new object of class '<em>EF Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Block</em>'.
   * @generated
   */
  EFBlock createEFBlock();

  /**
   * Returns a new object of class '<em>EF Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Statement</em>'.
   * @generated
   */
  EFStatement createEFStatement();

  /**
   * Returns a new object of class '<em>EF Return</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Return</em>'.
   * @generated
   */
  EFReturn createEFReturn();

  /**
   * Returns a new object of class '<em>EF If Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF If Statement</em>'.
   * @generated
   */
  EFIfStatement createEFIfStatement();

  /**
   * Returns a new object of class '<em>EF Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Expression</em>'.
   * @generated
   */
  EFExpression createEFExpression();

  /**
   * Returns a new object of class '<em>EF Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Rule</em>'.
   * @generated
   */
  EFRule createEFRule();

  /**
   * Returns a new object of class '<em>EF Rule Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Rule Class</em>'.
   * @generated
   */
  EFRuleClass createEFRuleClass();

  /**
   * Returns a new object of class '<em>EF Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Assignment</em>'.
   * @generated
   */
  EFAssignment createEFAssignment();

  /**
   * Returns a new object of class '<em>EF Or Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Or Expression</em>'.
   * @generated
   */
  EFOrExpression createEFOrExpression();

  /**
   * Returns a new object of class '<em>EF And Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF And Expression</em>'.
   * @generated
   */
  EFAndExpression createEFAndExpression();

  /**
   * Returns a new object of class '<em>EF Equal Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Equal Expression</em>'.
   * @generated
   */
  EFEqualExpression createEFEqualExpression();

  /**
   * Returns a new object of class '<em>EF Rel Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Rel Expression</em>'.
   * @generated
   */
  EFRelExpression createEFRelExpression();

  /**
   * Returns a new object of class '<em>EF Not Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Not Expression</em>'.
   * @generated
   */
  EFNotExpression createEFNotExpression();

  /**
   * Returns a new object of class '<em>EF String Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF String Constant</em>'.
   * @generated
   */
  EFStringConstant createEFStringConstant();

  /**
   * Returns a new object of class '<em>EF Int Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Int Constant</em>'.
   * @generated
   */
  EFIntConstant createEFIntConstant();

  /**
   * Returns a new object of class '<em>EF Bool Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Bool Constant</em>'.
   * @generated
   */
  EFBoolConstant createEFBoolConstant();

  /**
   * Returns a new object of class '<em>EF Primitive Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Primitive Type</em>'.
   * @generated
   */
  EFPrimitiveType createEFPrimitiveType();

  /**
   * Returns a new object of class '<em>EF This</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF This</em>'.
   * @generated
   */
  EFThis createEFThis();

  /**
   * Returns a new object of class '<em>EF Super</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Super</em>'.
   * @generated
   */
  EFSuper createEFSuper();

  /**
   * Returns a new object of class '<em>EF New</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF New</em>'.
   * @generated
   */
  EFNew createEFNew();

  /**
   * Returns a new object of class '<em>EFB Rackets Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EFB Rackets Expression</em>'.
   * @generated
   */
  EFBRacketsExpression createEFBRacketsExpression();

  /**
   * Returns a new object of class '<em>EF Function Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Function Call</em>'.
   * @generated
   */
  EFFunctionCall createEFFunctionCall();

  /**
   * Returns a new object of class '<em>EF Symbol Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Symbol Ref</em>'.
   * @generated
   */
  EFSymbolRef createEFSymbolRef();

  /**
   * Returns a new object of class '<em>EF Member Selection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Member Selection</em>'.
   * @generated
   */
  EFMemberSelection createEFMemberSelection();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  EasyWallPackage getEasyWallPackage();

} //EasyWallFactory
