/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Field</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFField()
 * @model
 * @generated
 */
public interface EFField extends EFMember
{
} // EFField
