/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Header</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFHeader#getRule <em>Rule</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFHeader#getFirewall <em>Firewall</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFHeader#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFHeader#getImports <em>Imports</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFHeader()
 * @model
 * @generated
 */
public interface EFHeader extends EFProgram
{
  /**
   * Returns the value of the '<em><b>Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule</em>' containment reference.
   * @see #setRule(EFRule)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFHeader_Rule()
   * @model containment="true"
   * @generated
   */
  EFRule getRule();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFHeader#getRule <em>Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rule</em>' containment reference.
   * @see #getRule()
   * @generated
   */
  void setRule(EFRule value);

  /**
   * Returns the value of the '<em><b>Firewall</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Firewall</em>' containment reference.
   * @see #setFirewall(EFfirewall)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFHeader_Firewall()
   * @model containment="true"
   * @generated
   */
  EFfirewall getFirewall();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFHeader#getFirewall <em>Firewall</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Firewall</em>' containment reference.
   * @see #getFirewall()
   * @generated
   */
  void setFirewall(EFfirewall value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFHeader_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFHeader#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.easywall.easyWall.EFImports}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFHeader_Imports()
   * @model containment="true"
   * @generated
   */
  EList<EFImports> getImports();

} // EFHeader
