/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Netmask Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFNetmaskConstant#getNetmask <em>Netmask</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFNetmaskConstant()
 * @model
 * @generated
 */
public interface EFNetmaskConstant extends EFExpression
{
  /**
   * Returns the value of the '<em><b>Netmask</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Netmask</em>' containment reference.
   * @see #setNetmask(EFExpression)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFNetmaskConstant_Netmask()
   * @model containment="true"
   * @generated
   */
  EFExpression getNetmask();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFNetmaskConstant#getNetmask <em>Netmask</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Netmask</em>' containment reference.
   * @see #getNetmask()
   * @generated
   */
  void setNetmask(EFExpression value);

} // EFNetmaskConstant
