/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Netport Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFNetportConstant#getPort <em>Port</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFNetportConstant()
 * @model
 * @generated
 */
public interface EFNetportConstant extends EFExpression
{
  /**
   * Returns the value of the '<em><b>Port</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' containment reference.
   * @see #setPort(EFExpression)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFNetportConstant_Port()
   * @model containment="true"
   * @generated
   */
  EFExpression getPort();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFNetportConstant#getPort <em>Port</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' containment reference.
   * @see #getPort()
   * @generated
   */
  void setPort(EFExpression value);

} // EFNetportConstant
