/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Primitive Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFPrimitiveType#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFPrimitiveType()
 * @model
 * @generated
 */
public interface EFPrimitiveType extends EFExpression
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.easywall.easyWall.EFNetworkNativeType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.easywall.easyWall.EFNetworkNativeType
   * @see #setType(EFNetworkNativeType)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFPrimitiveType_Type()
   * @model
   * @generated
   */
  EFNetworkNativeType getType();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFPrimitiveType#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.easywall.easyWall.EFNetworkNativeType
   * @see #getType()
   * @generated
   */
  void setType(EFNetworkNativeType value);

} // EFPrimitiveType
