/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Typed Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFTypedDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFTypedDeclaration#getRuletype <em>Ruletype</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFTypedDeclaration#getNativetype <em>Nativetype</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFTypedDeclaration#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFTypedDeclaration#getParams <em>Params</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFTypedDeclaration#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFTypedDeclaration()
 * @model
 * @generated
 */
public interface EFTypedDeclaration extends EFField, EFVariableDeclaration, EFMethod, EFParameter
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFTypedDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFTypedDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ruletype</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ruletype</em>' reference.
   * @see #setRuletype(EFRuleClass)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFTypedDeclaration_Ruletype()
   * @model
   * @generated
   */
  EFRuleClass getRuletype();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFTypedDeclaration#getRuletype <em>Ruletype</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ruletype</em>' reference.
   * @see #getRuletype()
   * @generated
   */
  void setRuletype(EFRuleClass value);

  /**
   * Returns the value of the '<em><b>Nativetype</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.easywall.easyWall.EFNetworkNativeType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nativetype</em>' attribute.
   * @see org.xtext.example.easywall.easyWall.EFNetworkNativeType
   * @see #setNativetype(EFNetworkNativeType)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFTypedDeclaration_Nativetype()
   * @model
   * @generated
   */
  EFNetworkNativeType getNativetype();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFTypedDeclaration#getNativetype <em>Nativetype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nativetype</em>' attribute.
   * @see org.xtext.example.easywall.easyWall.EFNetworkNativeType
   * @see #getNativetype()
   * @generated
   */
  void setNativetype(EFNetworkNativeType value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(EFExpression)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFTypedDeclaration_Expression()
   * @model containment="true"
   * @generated
   */
  EFExpression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFTypedDeclaration#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(EFExpression value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.easywall.easyWall.EFParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFTypedDeclaration_Params()
   * @model containment="true"
   * @generated
   */
  EList<EFParameter> getParams();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(EFBlock)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFTypedDeclaration_Body()
   * @model containment="true"
   * @generated
   */
  EFBlock getBody();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFTypedDeclaration#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(EFBlock value);

} // EFTypedDeclaration
