/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Variable Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFVariableDeclaration()
 * @model
 * @generated
 */
public interface EFVariableDeclaration extends EFStatement
{
} // EFVariableDeclaration
