/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtext.example.easywall.easyWall.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage
 * @generated
 */
public class EasyWallSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static EasyWallPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EasyWallSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = EasyWallPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case EasyWallPackage.EF_PROGRAM:
      {
        EFProgram efProgram = (EFProgram)theEObject;
        T result = caseEFProgram(efProgram);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_HEADER:
      {
        EFHeader efHeader = (EFHeader)theEObject;
        T result = caseEFHeader(efHeader);
        if (result == null) result = caseEFProgram(efHeader);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EFFIREWALL:
      {
        EFfirewall eFfirewall = (EFfirewall)theEObject;
        T result = caseEFfirewall(eFfirewall);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_IMPORTS:
      {
        EFImports efImports = (EFImports)theEObject;
        T result = caseEFImports(efImports);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_FIRE_CLASS:
      {
        EFFireClass efFireClass = (EFFireClass)theEObject;
        T result = caseEFFireClass(efFireClass);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_MEMBER:
      {
        EFMember efMember = (EFMember)theEObject;
        T result = caseEFMember(efMember);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_FIELD:
      {
        EFField efField = (EFField)theEObject;
        T result = caseEFField(efField);
        if (result == null) result = caseEFMember(efField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_VARIABLE_DECLARATION:
      {
        EFVariableDeclaration efVariableDeclaration = (EFVariableDeclaration)theEObject;
        T result = caseEFVariableDeclaration(efVariableDeclaration);
        if (result == null) result = caseEFField(efVariableDeclaration);
        if (result == null) result = caseEFStatement(efVariableDeclaration);
        if (result == null) result = caseEFMember(efVariableDeclaration);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_METHOD:
      {
        EFMethod efMethod = (EFMethod)theEObject;
        T result = caseEFMethod(efMethod);
        if (result == null) result = caseEFMember(efMethod);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_PARAMETER:
      {
        EFParameter efParameter = (EFParameter)theEObject;
        T result = caseEFParameter(efParameter);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_BLOCK:
      {
        EFBlock efBlock = (EFBlock)theEObject;
        T result = caseEFBlock(efBlock);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_STATEMENT:
      {
        EFStatement efStatement = (EFStatement)theEObject;
        T result = caseEFStatement(efStatement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_RETURN:
      {
        EFReturn efReturn = (EFReturn)theEObject;
        T result = caseEFReturn(efReturn);
        if (result == null) result = caseEFStatement(efReturn);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_IF_STATEMENT:
      {
        EFIfStatement efIfStatement = (EFIfStatement)theEObject;
        T result = caseEFIfStatement(efIfStatement);
        if (result == null) result = caseEFStatement(efIfStatement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_EXPRESSION:
      {
        EFExpression efExpression = (EFExpression)theEObject;
        T result = caseEFExpression(efExpression);
        if (result == null) result = caseEFStatement(efExpression);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_RULE:
      {
        EFRule efRule = (EFRule)theEObject;
        T result = caseEFRule(efRule);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_RULE_CLASS:
      {
        EFRuleClass efRuleClass = (EFRuleClass)theEObject;
        T result = caseEFRuleClass(efRuleClass);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_ASSIGNMENT:
      {
        EFAssignment efAssignment = (EFAssignment)theEObject;
        T result = caseEFAssignment(efAssignment);
        if (result == null) result = caseEFExpression(efAssignment);
        if (result == null) result = caseEFStatement(efAssignment);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_OR_EXPRESSION:
      {
        EFOrExpression efOrExpression = (EFOrExpression)theEObject;
        T result = caseEFOrExpression(efOrExpression);
        if (result == null) result = caseEFExpression(efOrExpression);
        if (result == null) result = caseEFStatement(efOrExpression);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_AND_EXPRESSION:
      {
        EFAndExpression efAndExpression = (EFAndExpression)theEObject;
        T result = caseEFAndExpression(efAndExpression);
        if (result == null) result = caseEFExpression(efAndExpression);
        if (result == null) result = caseEFStatement(efAndExpression);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_EQUAL_EXPRESSION:
      {
        EFEqualExpression efEqualExpression = (EFEqualExpression)theEObject;
        T result = caseEFEqualExpression(efEqualExpression);
        if (result == null) result = caseEFExpression(efEqualExpression);
        if (result == null) result = caseEFStatement(efEqualExpression);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_REL_EXPRESSION:
      {
        EFRelExpression efRelExpression = (EFRelExpression)theEObject;
        T result = caseEFRelExpression(efRelExpression);
        if (result == null) result = caseEFExpression(efRelExpression);
        if (result == null) result = caseEFStatement(efRelExpression);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_NOT_EXPRESSION:
      {
        EFNotExpression efNotExpression = (EFNotExpression)theEObject;
        T result = caseEFNotExpression(efNotExpression);
        if (result == null) result = caseEFExpression(efNotExpression);
        if (result == null) result = caseEFStatement(efNotExpression);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_STRING_CONSTANT:
      {
        EFStringConstant efStringConstant = (EFStringConstant)theEObject;
        T result = caseEFStringConstant(efStringConstant);
        if (result == null) result = caseEFExpression(efStringConstant);
        if (result == null) result = caseEFStatement(efStringConstant);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_INT_CONSTANT:
      {
        EFIntConstant efIntConstant = (EFIntConstant)theEObject;
        T result = caseEFIntConstant(efIntConstant);
        if (result == null) result = caseEFExpression(efIntConstant);
        if (result == null) result = caseEFStatement(efIntConstant);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_BOOL_CONSTANT:
      {
        EFBoolConstant efBoolConstant = (EFBoolConstant)theEObject;
        T result = caseEFBoolConstant(efBoolConstant);
        if (result == null) result = caseEFExpression(efBoolConstant);
        if (result == null) result = caseEFStatement(efBoolConstant);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_PRIMITIVE_TYPE:
      {
        EFPrimitiveType efPrimitiveType = (EFPrimitiveType)theEObject;
        T result = caseEFPrimitiveType(efPrimitiveType);
        if (result == null) result = caseEFExpression(efPrimitiveType);
        if (result == null) result = caseEFStatement(efPrimitiveType);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_DIRECTION_CONSTANT:
      {
        EFDirectionConstant efDirectionConstant = (EFDirectionConstant)theEObject;
        T result = caseEFDirectionConstant(efDirectionConstant);
        if (result == null) result = caseEFExpression(efDirectionConstant);
        if (result == null) result = caseEFStatement(efDirectionConstant);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_NETWORK_PROTOCOL_CONSTANT:
      {
        EFNetworkProtocolConstant efNetworkProtocolConstant = (EFNetworkProtocolConstant)theEObject;
        T result = caseEFNetworkProtocolConstant(efNetworkProtocolConstant);
        if (result == null) result = caseEFExpression(efNetworkProtocolConstant);
        if (result == null) result = caseEFStatement(efNetworkProtocolConstant);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_TRANSPORT_PROTOCOL_CONSTANT:
      {
        EFTransportProtocolConstant efTransportProtocolConstant = (EFTransportProtocolConstant)theEObject;
        T result = caseEFTransportProtocolConstant(efTransportProtocolConstant);
        if (result == null) result = caseEFExpression(efTransportProtocolConstant);
        if (result == null) result = caseEFStatement(efTransportProtocolConstant);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_APPLICATION_PROTOCOL_CONSTANT:
      {
        EFApplicationProtocolConstant efApplicationProtocolConstant = (EFApplicationProtocolConstant)theEObject;
        T result = caseEFApplicationProtocolConstant(efApplicationProtocolConstant);
        if (result == null) result = caseEFExpression(efApplicationProtocolConstant);
        if (result == null) result = caseEFStatement(efApplicationProtocolConstant);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_THIS:
      {
        EFThis efThis = (EFThis)theEObject;
        T result = caseEFThis(efThis);
        if (result == null) result = caseEFExpression(efThis);
        if (result == null) result = caseEFStatement(efThis);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_SUPER:
      {
        EFSuper efSuper = (EFSuper)theEObject;
        T result = caseEFSuper(efSuper);
        if (result == null) result = caseEFExpression(efSuper);
        if (result == null) result = caseEFStatement(efSuper);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_NEW:
      {
        EFNew efNew = (EFNew)theEObject;
        T result = caseEFNew(efNew);
        if (result == null) result = caseEFExpression(efNew);
        if (result == null) result = caseEFStatement(efNew);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EFB_RACKETS_EXPRESSION:
      {
        EFBRacketsExpression efbRacketsExpression = (EFBRacketsExpression)theEObject;
        T result = caseEFBRacketsExpression(efbRacketsExpression);
        if (result == null) result = caseEFExpression(efbRacketsExpression);
        if (result == null) result = caseEFStatement(efbRacketsExpression);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_FUNCTION_CALL:
      {
        EFFunctionCall efFunctionCall = (EFFunctionCall)theEObject;
        T result = caseEFFunctionCall(efFunctionCall);
        if (result == null) result = caseEFExpression(efFunctionCall);
        if (result == null) result = caseEFStatement(efFunctionCall);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_SYMBOL_REF:
      {
        EFSymbolRef efSymbolRef = (EFSymbolRef)theEObject;
        T result = caseEFSymbolRef(efSymbolRef);
        if (result == null) result = caseEFExpression(efSymbolRef);
        if (result == null) result = caseEFStatement(efSymbolRef);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case EasyWallPackage.EF_MEMBER_SELECTION:
      {
        EFMemberSelection efMemberSelection = (EFMemberSelection)theEObject;
        T result = caseEFMemberSelection(efMemberSelection);
        if (result == null) result = caseEFExpression(efMemberSelection);
        if (result == null) result = caseEFStatement(efMemberSelection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Program</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Program</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFProgram(EFProgram object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Header</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Header</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFHeader(EFHeader object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EFfirewall</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EFfirewall</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFfirewall(EFfirewall object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Imports</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Imports</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFImports(EFImports object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Fire Class</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Fire Class</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFFireClass(EFFireClass object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Member</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Member</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFMember(EFMember object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFField(EFField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Variable Declaration</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Variable Declaration</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFVariableDeclaration(EFVariableDeclaration object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Method</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Method</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFMethod(EFMethod object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Parameter</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Parameter</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFParameter(EFParameter object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Block</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Block</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFBlock(EFBlock object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFStatement(EFStatement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Return</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Return</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFReturn(EFReturn object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF If Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF If Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFIfStatement(EFIfStatement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Expression</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Expression</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFExpression(EFExpression object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Rule</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Rule</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFRule(EFRule object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Rule Class</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Rule Class</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFRuleClass(EFRuleClass object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Assignment</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Assignment</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFAssignment(EFAssignment object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Or Expression</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Or Expression</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFOrExpression(EFOrExpression object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF And Expression</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF And Expression</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFAndExpression(EFAndExpression object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Equal Expression</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Equal Expression</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFEqualExpression(EFEqualExpression object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Rel Expression</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Rel Expression</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFRelExpression(EFRelExpression object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Not Expression</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Not Expression</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFNotExpression(EFNotExpression object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF String Constant</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF String Constant</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFStringConstant(EFStringConstant object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Int Constant</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Int Constant</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFIntConstant(EFIntConstant object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Bool Constant</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Bool Constant</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFBoolConstant(EFBoolConstant object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Primitive Type</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Primitive Type</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFPrimitiveType(EFPrimitiveType object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Direction Constant</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Direction Constant</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFDirectionConstant(EFDirectionConstant object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Network Protocol Constant</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Network Protocol Constant</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFNetworkProtocolConstant(EFNetworkProtocolConstant object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Transport Protocol Constant</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Transport Protocol Constant</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFTransportProtocolConstant(EFTransportProtocolConstant object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Application Protocol Constant</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Application Protocol Constant</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFApplicationProtocolConstant(EFApplicationProtocolConstant object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF This</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF This</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFThis(EFThis object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Super</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Super</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFSuper(EFSuper object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF New</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF New</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFNew(EFNew object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EFB Rackets Expression</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EFB Rackets Expression</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFBRacketsExpression(EFBRacketsExpression object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Function Call</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Function Call</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFFunctionCall(EFFunctionCall object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Symbol Ref</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Symbol Ref</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFSymbolRef(EFSymbolRef object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EF Member Selection</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EF Member Selection</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEFMemberSelection(EFMemberSelection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //EasyWallSwitch
