/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.validation

import org.xtext.example.easywall.easyWall.EFRule
import org.eclipse.xtext.validation.Check
import com.google.inject.Inject
import org.xtext.example.easywall.EasyWallUtils
import org.xtext.example.easywall.easyWall.EasyWallPackage
import org.xtext.example.easywall.easyWall.EFNetworkNativeType
import org.xtext.example.easywall.easyWall.EFVariableDeclaration
import org.xtext.example.easywall.easyWall.EFNetworkProtocolConstant
import org.xtext.example.easywall.easyWall.EFTransportProtocolConstant
import org.xtext.example.easywall.easyWall.EFRulesTypes
import org.xtext.example.easywall.easyWall.EFApplicationProtocolConstant

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class EasyWallValidator extends AbstractEasyWallValidator {
	
	protected static val ISSUE_CODE_PREFIX = "org.xtext.example.easywall.";
	public static val MISSING_PROTOCOL = ISSUE_CODE_PREFIX + "MissingProtocol";
	public static val MISSING_DIRECTION = ISSUE_CODE_PREFIX + "MissingDirection";
	public static val BAD_DIRECTION = ISSUE_CODE_PREFIX + "BadDirection";
	public static val PROTOCOL_RULELAYER_MISMATCH = ISSUE_CODE_PREFIX + "ProtocolRulelayerMismatch";
	
	/* TODO */
	public static val IP_SYNTAX = ISSUE_CODE_PREFIX + "IPSyntax";
	public static val NETWORK_SYNTAX = ISSUE_CODE_PREFIX + "NetworkSyntax";
	public static val NETPORT_SYNTAX = ISSUE_CODE_PREFIX + "NetPortSyntax";
	
	@Inject extension EasyWallUtils
	
	@Check
	def checkMissingProtocol(EFRule rule){
		if(rule.ruleFields
			.filter[f | f.nativetype == EFNetworkNativeType.PROTOCOL]
			.map[f | f.name]
			.filter[n | n == "RULE_PROTOCOL"]
			.isEmpty) { 
				error("Rule " + rule.rules.name+ " is missing protocol", 
					EasyWallPackage.eINSTANCE.EFRuleClass_Members, 
					MISSING_PROTOCOL)
			}
	}
	
	@Check
	def checkTooManyProtocols(EFRule rule){
		if(rule.ruleFields
			.filter[f | f.nativetype == EFNetworkNativeType.PROTOCOL]
			.map[f | f.name]
			.filter[n | n == "RULE_PROTOCOL"]
			.length > 1) { 
				error("Rule " + rule.rules.name+ " has to many rule protocols", 
					EasyWallPackage.eINSTANCE.EFRuleClass_Members, 
					MISSING_PROTOCOL)
			}
	}
	
	@Check
	def checkMissingDirection(EFRule rule){
		if(rule.ruleFields
			.filter[f | f.nativetype == EFNetworkNativeType.DIRECTION]
			.map[f | f.name]
			.filter[n | n == "RULE_DIRECTION"]
			.isEmpty) { 
				error("Rule " + rule.rules.name+ " is missing direction (in/out)", 
					EasyWallPackage.eINSTANCE.EFRuleClass_Members, 
					MISSING_DIRECTION)
			}
	}	
	
	@Check
	def checkTooManyDirections(EFRule rule){
		if(rule.ruleFields
			.filter[f | f.nativetype == EFNetworkNativeType.DIRECTION]
			.map[f | f.name]
			.filter[n | n == "RULE_DIRECTION"]
			.length > 1) { 
				error("Rule " + rule.rules.name+ " has to many rule directions", 
					EasyWallPackage.eINSTANCE.EFRuleClass_Members, 
					MISSING_DIRECTION)
			}
	}	
	
	def checkProtocolMismatch(EFVariableDeclaration decl){
		var layer = decl.ruletype
		
		if(decl.nativetype == EFNetworkNativeType.PROTOCOL){
			var expr = decl.expression
			
			if((expr instanceof EFNetworkProtocolConstant && layer != EFRulesTypes.IPLEVEL) ||
				(expr instanceof EFTransportProtocolConstant && layer != EFRulesTypes.TRANSPLEVEL) ||
				(expr instanceof EFApplicationProtocolConstant && layer != EFRulesTypes.APPLEVEL)){
					var String protocol
					var String protocolLayer
					if(expr instanceof EFNetworkProtocolConstant){
						protocol = (expr as EFNetworkProtocolConstant).protocol.toString
						protocolLayer = "Network Layer"
					} else if(expr instanceof EFTransportProtocolConstant){
						protocol = (expr as EFTransportProtocolConstant).protocol.toString
						protocolLayer = "Transport Layer"
					} else if(expr instanceof EFApplicationProtocolConstant){
						protocol = (expr as EFApplicationProtocolConstant).protocol.toString
						protocolLayer = "Application Layer"
					}
					error("Protocol " + protocol + " does not match the layer defined for the rule.\nRule is at: " + layer +"\nProtocol defined is at: " + protocolLayer,
						EasyWallPackage.eINSTANCE.EFAssignment_Right,
						PROTOCOL_RULELAYER_MISMATCH)
			}
		}
	}
}
