/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.easywall.easyWall.EFExpression;
import org.xtext.example.easywall.easyWall.EasyWallPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EF Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFExpressionImpl#getFirst <em>First</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFExpressionImpl#getSecond <em>Second</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFExpressionImpl#getThird <em>Third</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFExpressionImpl#getFourth <em>Fourth</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFExpressionImpl#getAny <em>Any</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFExpressionImpl#getLocalhost <em>Localhost</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFExpressionImpl#getRawip <em>Rawip</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFExpressionImpl#getRawnetmask <em>Rawnetmask</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFExpressionImpl#getVarip <em>Varip</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFExpressionImpl#getVarnetmask <em>Varnetmask</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFExpressionImpl#getNetport <em>Netport</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EFExpressionImpl extends EFStatementImpl implements EFExpression
{
  /**
   * The default value of the '{@link #getFirst() <em>First</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFirst()
   * @generated
   * @ordered
   */
  protected static final int FIRST_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getFirst() <em>First</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFirst()
   * @generated
   * @ordered
   */
  protected int first = FIRST_EDEFAULT;

  /**
   * The default value of the '{@link #getSecond() <em>Second</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecond()
   * @generated
   * @ordered
   */
  protected static final int SECOND_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSecond() <em>Second</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecond()
   * @generated
   * @ordered
   */
  protected int second = SECOND_EDEFAULT;

  /**
   * The default value of the '{@link #getThird() <em>Third</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThird()
   * @generated
   * @ordered
   */
  protected static final int THIRD_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getThird() <em>Third</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThird()
   * @generated
   * @ordered
   */
  protected int third = THIRD_EDEFAULT;

  /**
   * The default value of the '{@link #getFourth() <em>Fourth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFourth()
   * @generated
   * @ordered
   */
  protected static final int FOURTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getFourth() <em>Fourth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFourth()
   * @generated
   * @ordered
   */
  protected int fourth = FOURTH_EDEFAULT;

  /**
   * The default value of the '{@link #getAny() <em>Any</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAny()
   * @generated
   * @ordered
   */
  protected static final String ANY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAny() <em>Any</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAny()
   * @generated
   * @ordered
   */
  protected String any = ANY_EDEFAULT;

  /**
   * The default value of the '{@link #getLocalhost() <em>Localhost</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocalhost()
   * @generated
   * @ordered
   */
  protected static final String LOCALHOST_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLocalhost() <em>Localhost</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocalhost()
   * @generated
   * @ordered
   */
  protected String localhost = LOCALHOST_EDEFAULT;

  /**
   * The cached value of the '{@link #getRawip() <em>Rawip</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRawip()
   * @generated
   * @ordered
   */
  protected EFExpression rawip;

  /**
   * The default value of the '{@link #getRawnetmask() <em>Rawnetmask</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRawnetmask()
   * @generated
   * @ordered
   */
  protected static final int RAWNETMASK_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRawnetmask() <em>Rawnetmask</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRawnetmask()
   * @generated
   * @ordered
   */
  protected int rawnetmask = RAWNETMASK_EDEFAULT;

  /**
   * The default value of the '{@link #getVarip() <em>Varip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarip()
   * @generated
   * @ordered
   */
  protected static final String VARIP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVarip() <em>Varip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarip()
   * @generated
   * @ordered
   */
  protected String varip = VARIP_EDEFAULT;

  /**
   * The default value of the '{@link #getVarnetmask() <em>Varnetmask</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarnetmask()
   * @generated
   * @ordered
   */
  protected static final String VARNETMASK_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVarnetmask() <em>Varnetmask</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarnetmask()
   * @generated
   * @ordered
   */
  protected String varnetmask = VARNETMASK_EDEFAULT;

  /**
   * The default value of the '{@link #getNetport() <em>Netport</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNetport()
   * @generated
   * @ordered
   */
  protected static final int NETPORT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNetport() <em>Netport</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNetport()
   * @generated
   * @ordered
   */
  protected int netport = NETPORT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EFExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EasyWallPackage.Literals.EF_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getFirst()
  {
    return first;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFirst(int newFirst)
  {
    int oldFirst = first;
    first = newFirst;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_EXPRESSION__FIRST, oldFirst, first));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSecond()
  {
    return second;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSecond(int newSecond)
  {
    int oldSecond = second;
    second = newSecond;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_EXPRESSION__SECOND, oldSecond, second));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getThird()
  {
    return third;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setThird(int newThird)
  {
    int oldThird = third;
    third = newThird;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_EXPRESSION__THIRD, oldThird, third));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getFourth()
  {
    return fourth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFourth(int newFourth)
  {
    int oldFourth = fourth;
    fourth = newFourth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_EXPRESSION__FOURTH, oldFourth, fourth));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAny()
  {
    return any;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAny(String newAny)
  {
    String oldAny = any;
    any = newAny;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_EXPRESSION__ANY, oldAny, any));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLocalhost()
  {
    return localhost;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLocalhost(String newLocalhost)
  {
    String oldLocalhost = localhost;
    localhost = newLocalhost;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_EXPRESSION__LOCALHOST, oldLocalhost, localhost));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFExpression getRawip()
  {
    return rawip;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRawip(EFExpression newRawip, NotificationChain msgs)
  {
    EFExpression oldRawip = rawip;
    rawip = newRawip;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_EXPRESSION__RAWIP, oldRawip, newRawip);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRawip(EFExpression newRawip)
  {
    if (newRawip != rawip)
    {
      NotificationChain msgs = null;
      if (rawip != null)
        msgs = ((InternalEObject)rawip).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EF_EXPRESSION__RAWIP, null, msgs);
      if (newRawip != null)
        msgs = ((InternalEObject)newRawip).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EF_EXPRESSION__RAWIP, null, msgs);
      msgs = basicSetRawip(newRawip, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_EXPRESSION__RAWIP, newRawip, newRawip));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getRawnetmask()
  {
    return rawnetmask;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRawnetmask(int newRawnetmask)
  {
    int oldRawnetmask = rawnetmask;
    rawnetmask = newRawnetmask;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_EXPRESSION__RAWNETMASK, oldRawnetmask, rawnetmask));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVarip()
  {
    return varip;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarip(String newVarip)
  {
    String oldVarip = varip;
    varip = newVarip;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_EXPRESSION__VARIP, oldVarip, varip));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVarnetmask()
  {
    return varnetmask;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarnetmask(String newVarnetmask)
  {
    String oldVarnetmask = varnetmask;
    varnetmask = newVarnetmask;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_EXPRESSION__VARNETMASK, oldVarnetmask, varnetmask));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNetport()
  {
    return netport;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNetport(int newNetport)
  {
    int oldNetport = netport;
    netport = newNetport;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_EXPRESSION__NETPORT, oldNetport, netport));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_EXPRESSION__RAWIP:
        return basicSetRawip(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_EXPRESSION__FIRST:
        return getFirst();
      case EasyWallPackage.EF_EXPRESSION__SECOND:
        return getSecond();
      case EasyWallPackage.EF_EXPRESSION__THIRD:
        return getThird();
      case EasyWallPackage.EF_EXPRESSION__FOURTH:
        return getFourth();
      case EasyWallPackage.EF_EXPRESSION__ANY:
        return getAny();
      case EasyWallPackage.EF_EXPRESSION__LOCALHOST:
        return getLocalhost();
      case EasyWallPackage.EF_EXPRESSION__RAWIP:
        return getRawip();
      case EasyWallPackage.EF_EXPRESSION__RAWNETMASK:
        return getRawnetmask();
      case EasyWallPackage.EF_EXPRESSION__VARIP:
        return getVarip();
      case EasyWallPackage.EF_EXPRESSION__VARNETMASK:
        return getVarnetmask();
      case EasyWallPackage.EF_EXPRESSION__NETPORT:
        return getNetport();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_EXPRESSION__FIRST:
        setFirst((Integer)newValue);
        return;
      case EasyWallPackage.EF_EXPRESSION__SECOND:
        setSecond((Integer)newValue);
        return;
      case EasyWallPackage.EF_EXPRESSION__THIRD:
        setThird((Integer)newValue);
        return;
      case EasyWallPackage.EF_EXPRESSION__FOURTH:
        setFourth((Integer)newValue);
        return;
      case EasyWallPackage.EF_EXPRESSION__ANY:
        setAny((String)newValue);
        return;
      case EasyWallPackage.EF_EXPRESSION__LOCALHOST:
        setLocalhost((String)newValue);
        return;
      case EasyWallPackage.EF_EXPRESSION__RAWIP:
        setRawip((EFExpression)newValue);
        return;
      case EasyWallPackage.EF_EXPRESSION__RAWNETMASK:
        setRawnetmask((Integer)newValue);
        return;
      case EasyWallPackage.EF_EXPRESSION__VARIP:
        setVarip((String)newValue);
        return;
      case EasyWallPackage.EF_EXPRESSION__VARNETMASK:
        setVarnetmask((String)newValue);
        return;
      case EasyWallPackage.EF_EXPRESSION__NETPORT:
        setNetport((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_EXPRESSION__FIRST:
        setFirst(FIRST_EDEFAULT);
        return;
      case EasyWallPackage.EF_EXPRESSION__SECOND:
        setSecond(SECOND_EDEFAULT);
        return;
      case EasyWallPackage.EF_EXPRESSION__THIRD:
        setThird(THIRD_EDEFAULT);
        return;
      case EasyWallPackage.EF_EXPRESSION__FOURTH:
        setFourth(FOURTH_EDEFAULT);
        return;
      case EasyWallPackage.EF_EXPRESSION__ANY:
        setAny(ANY_EDEFAULT);
        return;
      case EasyWallPackage.EF_EXPRESSION__LOCALHOST:
        setLocalhost(LOCALHOST_EDEFAULT);
        return;
      case EasyWallPackage.EF_EXPRESSION__RAWIP:
        setRawip((EFExpression)null);
        return;
      case EasyWallPackage.EF_EXPRESSION__RAWNETMASK:
        setRawnetmask(RAWNETMASK_EDEFAULT);
        return;
      case EasyWallPackage.EF_EXPRESSION__VARIP:
        setVarip(VARIP_EDEFAULT);
        return;
      case EasyWallPackage.EF_EXPRESSION__VARNETMASK:
        setVarnetmask(VARNETMASK_EDEFAULT);
        return;
      case EasyWallPackage.EF_EXPRESSION__NETPORT:
        setNetport(NETPORT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_EXPRESSION__FIRST:
        return first != FIRST_EDEFAULT;
      case EasyWallPackage.EF_EXPRESSION__SECOND:
        return second != SECOND_EDEFAULT;
      case EasyWallPackage.EF_EXPRESSION__THIRD:
        return third != THIRD_EDEFAULT;
      case EasyWallPackage.EF_EXPRESSION__FOURTH:
        return fourth != FOURTH_EDEFAULT;
      case EasyWallPackage.EF_EXPRESSION__ANY:
        return ANY_EDEFAULT == null ? any != null : !ANY_EDEFAULT.equals(any);
      case EasyWallPackage.EF_EXPRESSION__LOCALHOST:
        return LOCALHOST_EDEFAULT == null ? localhost != null : !LOCALHOST_EDEFAULT.equals(localhost);
      case EasyWallPackage.EF_EXPRESSION__RAWIP:
        return rawip != null;
      case EasyWallPackage.EF_EXPRESSION__RAWNETMASK:
        return rawnetmask != RAWNETMASK_EDEFAULT;
      case EasyWallPackage.EF_EXPRESSION__VARIP:
        return VARIP_EDEFAULT == null ? varip != null : !VARIP_EDEFAULT.equals(varip);
      case EasyWallPackage.EF_EXPRESSION__VARNETMASK:
        return VARNETMASK_EDEFAULT == null ? varnetmask != null : !VARNETMASK_EDEFAULT.equals(varnetmask);
      case EasyWallPackage.EF_EXPRESSION__NETPORT:
        return netport != NETPORT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (first: ");
    result.append(first);
    result.append(", second: ");
    result.append(second);
    result.append(", third: ");
    result.append(third);
    result.append(", fourth: ");
    result.append(fourth);
    result.append(", any: ");
    result.append(any);
    result.append(", localhost: ");
    result.append(localhost);
    result.append(", rawnetmask: ");
    result.append(rawnetmask);
    result.append(", varip: ");
    result.append(varip);
    result.append(", varnetmask: ");
    result.append(varnetmask);
    result.append(", netport: ");
    result.append(netport);
    result.append(')');
    return result.toString();
  }

} //EFExpressionImpl
