/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.easywall.easyWall.EFFireClass;
import org.xtext.example.easywall.easyWall.EFfirewall;
import org.xtext.example.easywall.easyWall.EasyWallPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EFfirewall</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFfirewallImpl#getFirewall <em>Firewall</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EFfirewallImpl extends MinimalEObjectImpl.Container implements EFfirewall
{
  /**
   * The cached value of the '{@link #getFirewall() <em>Firewall</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFirewall()
   * @generated
   * @ordered
   */
  protected EFFireClass firewall;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EFfirewallImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EasyWallPackage.Literals.EFFIREWALL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFFireClass getFirewall()
  {
    return firewall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFirewall(EFFireClass newFirewall, NotificationChain msgs)
  {
    EFFireClass oldFirewall = firewall;
    firewall = newFirewall;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EasyWallPackage.EFFIREWALL__FIREWALL, oldFirewall, newFirewall);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFirewall(EFFireClass newFirewall)
  {
    if (newFirewall != firewall)
    {
      NotificationChain msgs = null;
      if (firewall != null)
        msgs = ((InternalEObject)firewall).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EFFIREWALL__FIREWALL, null, msgs);
      if (newFirewall != null)
        msgs = ((InternalEObject)newFirewall).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EFFIREWALL__FIREWALL, null, msgs);
      msgs = basicSetFirewall(newFirewall, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EFFIREWALL__FIREWALL, newFirewall, newFirewall));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EasyWallPackage.EFFIREWALL__FIREWALL:
        return basicSetFirewall(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EasyWallPackage.EFFIREWALL__FIREWALL:
        return getFirewall();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EasyWallPackage.EFFIREWALL__FIREWALL:
        setFirewall((EFFireClass)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EFFIREWALL__FIREWALL:
        setFirewall((EFFireClass)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EFFIREWALL__FIREWALL:
        return firewall != null;
    }
    return super.eIsSet(featureID);
  }

} //EFfirewallImpl
