/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.easywall.easyWall.EFExpression;
import org.xtext.example.easywall.easyWall.EFIPv4Constant;
import org.xtext.example.easywall.easyWall.EasyWallPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EFI Pv4 Constant</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFIPv4ConstantImpl#getIpv4 <em>Ipv4</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EFIPv4ConstantImpl extends EFExpressionImpl implements EFIPv4Constant
{
  /**
   * The cached value of the '{@link #getIpv4() <em>Ipv4</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIpv4()
   * @generated
   * @ordered
   */
  protected EFExpression ipv4;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EFIPv4ConstantImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EasyWallPackage.Literals.EFI_PV4_CONSTANT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFExpression getIpv4()
  {
    return ipv4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIpv4(EFExpression newIpv4, NotificationChain msgs)
  {
    EFExpression oldIpv4 = ipv4;
    ipv4 = newIpv4;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EasyWallPackage.EFI_PV4_CONSTANT__IPV4, oldIpv4, newIpv4);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIpv4(EFExpression newIpv4)
  {
    if (newIpv4 != ipv4)
    {
      NotificationChain msgs = null;
      if (ipv4 != null)
        msgs = ((InternalEObject)ipv4).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EFI_PV4_CONSTANT__IPV4, null, msgs);
      if (newIpv4 != null)
        msgs = ((InternalEObject)newIpv4).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EFI_PV4_CONSTANT__IPV4, null, msgs);
      msgs = basicSetIpv4(newIpv4, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EFI_PV4_CONSTANT__IPV4, newIpv4, newIpv4));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EasyWallPackage.EFI_PV4_CONSTANT__IPV4:
        return basicSetIpv4(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EasyWallPackage.EFI_PV4_CONSTANT__IPV4:
        return getIpv4();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EasyWallPackage.EFI_PV4_CONSTANT__IPV4:
        setIpv4((EFExpression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EFI_PV4_CONSTANT__IPV4:
        setIpv4((EFExpression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EFI_PV4_CONSTANT__IPV4:
        return ipv4 != null;
    }
    return super.eIsSet(featureID);
  }

} //EFIPv4ConstantImpl
