/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.easywall.easyWall.EFMethod;
import org.xtext.example.easywall.easyWall.EasyWallPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EF Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EFMethodImpl extends EFMemberImpl implements EFMethod
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EFMethodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EasyWallPackage.Literals.EF_METHOD;
  }

} //EFMethodImpl
