/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.easyWall.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.easywall.easyWall.EFBlock;
import org.xtext.example.easywall.easyWall.EFExpression;
import org.xtext.example.easywall.easyWall.EFNetworkNativeType;
import org.xtext.example.easywall.easyWall.EFParameter;
import org.xtext.example.easywall.easyWall.EFRuleClass;
import org.xtext.example.easywall.easyWall.EFTypedDeclaration;
import org.xtext.example.easywall.easyWall.EasyWallPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EF Typed Declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFTypedDeclarationImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFTypedDeclarationImpl#getRuletype <em>Ruletype</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFTypedDeclarationImpl#getNativetype <em>Nativetype</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFTypedDeclarationImpl#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFTypedDeclarationImpl#getParams <em>Params</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFTypedDeclarationImpl#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EFTypedDeclarationImpl extends EFFieldImpl implements EFTypedDeclaration
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getRuletype() <em>Ruletype</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRuletype()
   * @generated
   * @ordered
   */
  protected EFRuleClass ruletype;

  /**
   * The default value of the '{@link #getNativetype() <em>Nativetype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNativetype()
   * @generated
   * @ordered
   */
  protected static final EFNetworkNativeType NATIVETYPE_EDEFAULT = EFNetworkNativeType.NETWORK;

  /**
   * The cached value of the '{@link #getNativetype() <em>Nativetype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNativetype()
   * @generated
   * @ordered
   */
  protected EFNetworkNativeType nativetype = NATIVETYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getExpression() <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpression()
   * @generated
   * @ordered
   */
  protected EFExpression expression;

  /**
   * The cached value of the '{@link #getParams() <em>Params</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParams()
   * @generated
   * @ordered
   */
  protected EList<EFParameter> params;

  /**
   * The cached value of the '{@link #getBody() <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBody()
   * @generated
   * @ordered
   */
  protected EFBlock body;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EFTypedDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EasyWallPackage.Literals.EF_TYPED_DECLARATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_TYPED_DECLARATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFRuleClass getRuletype()
  {
    if (ruletype != null && ruletype.eIsProxy())
    {
      InternalEObject oldRuletype = (InternalEObject)ruletype;
      ruletype = (EFRuleClass)eResolveProxy(oldRuletype);
      if (ruletype != oldRuletype)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, EasyWallPackage.EF_TYPED_DECLARATION__RULETYPE, oldRuletype, ruletype));
      }
    }
    return ruletype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EFRuleClass basicGetRuletype()
  {
    return ruletype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRuletype(EFRuleClass newRuletype)
  {
    EFRuleClass oldRuletype = ruletype;
    ruletype = newRuletype;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_TYPED_DECLARATION__RULETYPE, oldRuletype, ruletype));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFNetworkNativeType getNativetype()
  {
    return nativetype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNativetype(EFNetworkNativeType newNativetype)
  {
    EFNetworkNativeType oldNativetype = nativetype;
    nativetype = newNativetype == null ? NATIVETYPE_EDEFAULT : newNativetype;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_TYPED_DECLARATION__NATIVETYPE, oldNativetype, nativetype));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFExpression getExpression()
  {
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpression(EFExpression newExpression, NotificationChain msgs)
  {
    EFExpression oldExpression = expression;
    expression = newExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_TYPED_DECLARATION__EXPRESSION, oldExpression, newExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExpression(EFExpression newExpression)
  {
    if (newExpression != expression)
    {
      NotificationChain msgs = null;
      if (expression != null)
        msgs = ((InternalEObject)expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EF_TYPED_DECLARATION__EXPRESSION, null, msgs);
      if (newExpression != null)
        msgs = ((InternalEObject)newExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EF_TYPED_DECLARATION__EXPRESSION, null, msgs);
      msgs = basicSetExpression(newExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_TYPED_DECLARATION__EXPRESSION, newExpression, newExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EFParameter> getParams()
  {
    if (params == null)
    {
      params = new EObjectContainmentEList<EFParameter>(EFParameter.class, this, EasyWallPackage.EF_TYPED_DECLARATION__PARAMS);
    }
    return params;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFBlock getBody()
  {
    return body;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBody(EFBlock newBody, NotificationChain msgs)
  {
    EFBlock oldBody = body;
    body = newBody;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_TYPED_DECLARATION__BODY, oldBody, newBody);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBody(EFBlock newBody)
  {
    if (newBody != body)
    {
      NotificationChain msgs = null;
      if (body != null)
        msgs = ((InternalEObject)body).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EF_TYPED_DECLARATION__BODY, null, msgs);
      if (newBody != null)
        msgs = ((InternalEObject)newBody).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EF_TYPED_DECLARATION__BODY, null, msgs);
      msgs = basicSetBody(newBody, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_TYPED_DECLARATION__BODY, newBody, newBody));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_TYPED_DECLARATION__EXPRESSION:
        return basicSetExpression(null, msgs);
      case EasyWallPackage.EF_TYPED_DECLARATION__PARAMS:
        return ((InternalEList<?>)getParams()).basicRemove(otherEnd, msgs);
      case EasyWallPackage.EF_TYPED_DECLARATION__BODY:
        return basicSetBody(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_TYPED_DECLARATION__NAME:
        return getName();
      case EasyWallPackage.EF_TYPED_DECLARATION__RULETYPE:
        if (resolve) return getRuletype();
        return basicGetRuletype();
      case EasyWallPackage.EF_TYPED_DECLARATION__NATIVETYPE:
        return getNativetype();
      case EasyWallPackage.EF_TYPED_DECLARATION__EXPRESSION:
        return getExpression();
      case EasyWallPackage.EF_TYPED_DECLARATION__PARAMS:
        return getParams();
      case EasyWallPackage.EF_TYPED_DECLARATION__BODY:
        return getBody();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_TYPED_DECLARATION__NAME:
        setName((String)newValue);
        return;
      case EasyWallPackage.EF_TYPED_DECLARATION__RULETYPE:
        setRuletype((EFRuleClass)newValue);
        return;
      case EasyWallPackage.EF_TYPED_DECLARATION__NATIVETYPE:
        setNativetype((EFNetworkNativeType)newValue);
        return;
      case EasyWallPackage.EF_TYPED_DECLARATION__EXPRESSION:
        setExpression((EFExpression)newValue);
        return;
      case EasyWallPackage.EF_TYPED_DECLARATION__PARAMS:
        getParams().clear();
        getParams().addAll((Collection<? extends EFParameter>)newValue);
        return;
      case EasyWallPackage.EF_TYPED_DECLARATION__BODY:
        setBody((EFBlock)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_TYPED_DECLARATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EasyWallPackage.EF_TYPED_DECLARATION__RULETYPE:
        setRuletype((EFRuleClass)null);
        return;
      case EasyWallPackage.EF_TYPED_DECLARATION__NATIVETYPE:
        setNativetype(NATIVETYPE_EDEFAULT);
        return;
      case EasyWallPackage.EF_TYPED_DECLARATION__EXPRESSION:
        setExpression((EFExpression)null);
        return;
      case EasyWallPackage.EF_TYPED_DECLARATION__PARAMS:
        getParams().clear();
        return;
      case EasyWallPackage.EF_TYPED_DECLARATION__BODY:
        setBody((EFBlock)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_TYPED_DECLARATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EasyWallPackage.EF_TYPED_DECLARATION__RULETYPE:
        return ruletype != null;
      case EasyWallPackage.EF_TYPED_DECLARATION__NATIVETYPE:
        return nativetype != NATIVETYPE_EDEFAULT;
      case EasyWallPackage.EF_TYPED_DECLARATION__EXPRESSION:
        return expression != null;
      case EasyWallPackage.EF_TYPED_DECLARATION__PARAMS:
        return params != null && !params.isEmpty();
      case EasyWallPackage.EF_TYPED_DECLARATION__BODY:
        return body != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", nativetype: ");
    result.append(nativetype);
    result.append(')');
    return result.toString();
  }

} //EFTypedDeclarationImpl
