/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EasyWallValidator extends AbstractEasyWallValidator {
  protected static final String ISSUE_CODE_PREFIX = "org.xtext.example.easywall.";

  public static final String MISSING_PROTOCOL = (EasyWallValidator.ISSUE_CODE_PREFIX + "MissingProtocol");

  public static final String MISSING_DIRECTION = (EasyWallValidator.ISSUE_CODE_PREFIX + "MissingDirection");
}
