/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EasyWallStandaloneSetup extends EasyWallStandaloneSetupGenerated {
  public static void doSetup() {
    new EasyWallStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
