/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EasyWallAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/easywall/parser/antlr/internal/InternalEasyWall.tokens");
	}
}
